pipeline {
    agent any
    
    environment {
        APP_DIR = 'messaging_app'
    }
    
    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'github-credentials', 
                    url: 'https://github.com/calebomariba/alx-backend-python.git',
                    git branch: 'main'
            }
        }
        
        stage('Setup Python Environment') {
            steps {
                dir("${APP_DIR}") {
                    sh '''
                        python -m venv venv
                        . venv/bin/activate
                        pip3 install -r messaging_app/requirements.txt
                    '''
                }
            }
        }
        
        stage('Run Tests') {
            steps {
                dir("${APP_DIR}") {
                    sh '''
                        . venv/bin/activate
                        pytest test_simple.py -v -s --junitxml=test-results.xml
                    '''
                }
            }
        }
        
        stage('Generate Report') {
            steps {
                publishTestResults testResultsPattern: "${APP_DIR}/test-results.xml"
            }
        }
    }
    
    post {
        success {
            echo "All tests passed successfully!"
        }
    }
}