pipeline {
    agent any

    tools {
        python 'Python 3' // Ensure this is defined in Jenkins tools
    }

    environment {
        VENV_DIR = 'venv'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git credentialsId: 'your-credentials-id', url: 'https://github.com/calebomariba/alx-backend-python.git'
            }
        }

        stage('Set Up Python') {
            steps {
                sh 'python3 -m venv $VENV_DIR'
                sh '. $VENV_DIR/bin/activate && pip install --upgrade pip && pip install -r messaging_app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh '. $VENV_DIR/bin/activate && pytest messaging_app/tests --junitxml=report.xml'
            }
        }

        stage('Publish Report') {
            steps {
                junit 'report.xml'
            }
        }
    }

    options {
        skipDefaultCheckout(true)
    }
}
